words = [
    "ASID",
    "Armv",
    "BCM",
    "BSP",
    "BSS",
    "CNTP",
    "Consolas",
    "DAIF",
    "DTB",
    "ELR",
    "FDT",
    "FIF",
    "FIQ",
    "FQDT",
    "GIC",
    "HCE",
    "HCR",
    "HVC",
    "Lbss",
    "Lcheck",
    "Lclear",
    "Lconfigure",
    "Lentered",
    "Lpark",
    "Lsave",
    "Lvector",
    "MAIR",
    "MMC",
    "MMIO",
    "MMU",
    "MPIDR",
    "Menlo",
    "NOLOAD",
    "OOM",
    "QEMU",
    "RXE",
    "SCTLR",
    "SPSR",
    "Segoe",
    "TCR",
    "TLB",
    "TTBR",
    "TXE",
    "TXFF",
    "UART",
    "UARTCR",
    "UARTDR",
    "UARTEN",
    "UARTFBRD",
    "UARTFR",
    "UARTIBRD",
    "UARTICR",
    "UARTLCR",
    "VBAR",
    "WLEN",
    "adr",
    "balign",
    "beb",
    "breakpoint",
    "brk",
    "cbnz",
    "coreutils",
    "deinit",
    "endm",
    "eret",
    "fba",
    "initramfs",
    "inspectable",
    "isb",
    "kcov",
    "ldp",
    "ldr",
    "lede",
    "lsr",
    "msr",
    "nixpkgs",
    "nographic",
    "optionals",
    "pkgs",
    "raspi",
    "rodata",
    "rpi",
    "scriptable",
    "semihost",
    "stdenv",
    "stp",
    "svc",
    "syscall",
    "syscalls",
    "thekorn",
    "topbar",
    "ubfx",
    "userspace",
    "virt",
    "virtio",
    "wfe",
    "xffffff",
    "xzr",
    "zigpkgs",
    "zlinter",
    "zls",
    "zon",
]
ignore_paths = ["flake.lock"]
