words = [
    "ASID",
    "AAJXIWQ",
    "Armv",
    "BCM",
    "BSP",
    "BSS",
    "Broadcom",
    "CNTP",
    "CNTFRQ",
    "CPACR",
    "Clr",
    "Consolas",
    "DAIF",
    "DAIFClr",
    "DDI",
    "DOUT",
    "DuPont",
    "DTB",
    "dtbo",
    "dtoverlay",
    "EEPROM",
    "ELR",
    "FDT",
    "FMOV",
    "FTDI",
    "FIF",
    "FIQ",
    "FQDT",
    "GIC",
    "GND",
    "HCE",
    "HCR",
    "HVC",
    "Lbss",
    "Lcheck",
    "Lclear",
    "Lconfigure",
    "Lentered",
    "Lmmu",
    "Lpark",
    "Lsave",
    "Luser",
    "Lvector",
    "MAIR",
    "MBR",
    "MMC",
    "MMIO",
    "MMFR",
    "MMU",
    "MPIDR",
    "MOSI",
    "Menlo",
    "NOLOAD",
    "OOM",
    "PHDRS",
    "Pont",
    "PWM",
    "QEMU",
    "RXE",
    "RXD",
    "SCHED",
    "SCL",
    "SCLK",
    "SDA",
    "SCTLR",
    "SPSR",
    "Segoe",
    "TCR",
    "TVAL",
    "TLB",
    "TTBR",
    "TXE",
    "TXFF",
    "TXD",
    "UART",
    "UARTCR",
    "UARTDR",
    "UARTEN",
    "UARTFBRD",
    "UARTFR",
    "UARTIBRD",
    "UARTICR",
    "UARTLCR",
    "VBAR",
    "VCC",
    "VMS",
    "VPU",
    "YGW",
    "WLEN",
    "WXN",
    "adr",
    "balign",
    "beb",
    "bootable",
    "bootcode",
    "breakpoint",
    "brk",
    "bytearray",
    "cbnz",
    "cmn",
    "cmdline",
    "cpio",
    "coreutils",
    "deinit",
    "dialout",
    "dma",
    "dmb",
    "dsb",
    "endm",
    "equ",
    "eret",
    "fba",
    "fixup",
    "flashable",
    "Imager",
    "initramfs",
    "inspectable",
    "iallu",
    "isb",
    "kcov",
    "kxa",
    "lba",
    "ldp",
    "ldr",
    "lede",
    "linecap",
    "lsl",
    "lsr",
    "msr",
    "movz",
    "muxing",
    "mkdir",
    "minicom",
    "mtools",
    "newc",
    "nixpkgs",
    "nographic",
    "osh",
    "oshst",
    "optionals",
    "PCM",
    "picocom",
    "pinout",
    "pkgs",
    "preemptions",
    "raspi",
    "raspberrypi",
    "rodata",
    "rpi",
    "srgb",
    "scriptable",
    "semihost",
    "stdenv",
    "stp",
    "svc",
    "syscall",
    "syscalls",
    "thekorn",
    "tlbi",
    "topbar",
    "ubfx",
    "userspace",
    "usbmodem",
    "usbserial",
    "virt",
    "virtio",
    "vmalle",
    "wfe",
    "xaa",
    "xeb",
    "xfe",
    "xffffff",
    "xzr",
    "zigpkgs",
    "zlinter",
    "zls",
    "zon",
]
ignore_paths = ["flake.lock"]
